BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SALE CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SALESMAN CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MANAGER CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE MANAGER (
    ID_MANAGER NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MANAGER PRIMARY KEY (ID_MANAGER),
    CONSTRAINT UK_MANAGER_CPF UNIQUE (CPF)
);

CREATE TABLE CUSTOMER (
    ID_CUSTOMER NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID_CUSTOMER),
    CONSTRAINT UK_CUSTOMER_CPF UNIQUE (CPF)
);

CREATE TABLE SALESMAN (
    ID_SALESMAN NUMBER GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_SALESMAN PRIMARY KEY (ID_SALESMAN),
    CONSTRAINT UK_SALESMAN_CPF UNIQUE (CPF)
);

CREATE TABLE SALE (
    ID_SALE NUMBER GENERATED ALWAYS AS IDENTITY,
    FK_SALESMAN NUMBER NOT NULL,
    FK_CUSTOMER NUMBER NOT NULL,
    IS_STARTED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_FINISHED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_SALE PRIMARY KEY (ID_SALE),
    CONSTRAINT FK_SALE_SALESMAN FOREIGN KEY (FK_SALESMAN)
        REFERENCES SALESMAN (ID_SALESMAN),
    CONSTRAINT FK_SALE_CUSTOMER FOREIGN KEY (FK_CUSTOMER)
        REFERENCES CUSTOMER (ID_CUSTOMER),
    CONSTRAINT CK_SALE_STARTED CHECK (IS_STARTED IN (0, 1)),
    CONSTRAINT CK_SALE_FINISHED CHECK (IS_FINISHED IN (0, 1)),
    CONSTRAINT CK_SALE_STATE CHECK (IS_FINISHED = 0 OR IS_STARTED = 1)
);
